-- ═══════════════════════════════════════════════════════════════════════════
-- NSE Trading Platform — SQLite Schema
-- All timestamps stored as epoch milliseconds (IST).
-- Every table includes user_id for future multi-user support.
-- Run once at DB creation; DBWriter auto-detects existing tables.
-- ═══════════════════════════════════════════════════════════════════════════

PRAGMA journal_mode = WAL;
PRAGMA foreign_keys = ON;
PRAGMA busy_timeout = 5000;

-- ── Users ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
    user_id         TEXT PRIMARY KEY,
    display_name    TEXT NOT NULL DEFAULT '',
    created_at      INTEGER NOT NULL,           -- epoch ms
    is_active       INTEGER NOT NULL DEFAULT 1  -- 1=active, 0=disabled
);

-- ── System State (one row per user — upserted by engine) ─────────────────
CREATE TABLE IF NOT EXISTS system_state (
    user_id             TEXT PRIMARY KEY REFERENCES users(user_id),
    engine_status       TEXT NOT NULL DEFAULT 'STOPPED',  -- STOPPED | WARMING_UP | RUNNING | PAUSED | KILLED
    active_strategy     TEXT NOT NULL DEFAULT '',
    current_positions   INTEGER NOT NULL DEFAULT 0,
    daily_pnl           REAL NOT NULL DEFAULT 0.0,
    daily_trades        INTEGER NOT NULL DEFAULT 0,
    kill_switch_active  INTEGER NOT NULL DEFAULT 0,
    last_tick_at        INTEGER,                          -- epoch ms of last processed tick
    last_signal         TEXT NOT NULL DEFAULT '',
    last_signal_at      INTEGER,
    updated_at          INTEGER NOT NULL
);

-- ── Trade Plans (pre-trade intent — before order placement) ──────────────
CREATE TABLE IF NOT EXISTS trade_plans (
    plan_id         TEXT PRIMARY KEY,
    user_id         TEXT NOT NULL REFERENCES users(user_id),
    strategy_name   TEXT NOT NULL,                -- e.g. 'orb_vwap', 'sd_zones'
    symbol          TEXT NOT NULL,                -- e.g. 'NSE:RELIANCE-EQ'
    direction       TEXT NOT NULL,                -- BUY | SELL
    entry_price     REAL NOT NULL,
    stoploss_price  REAL NOT NULL,
    target_price    REAL,
    quantity         INTEGER NOT NULL,
    risk_amount     REAL NOT NULL,                -- INR at risk
    reward_amount   REAL,
    rr_ratio        REAL,
    plan_metadata   TEXT NOT NULL DEFAULT '{}',   -- JSON: ORB levels, zone info, etc.
    status          TEXT NOT NULL DEFAULT 'PENDING',  -- PENDING | EXECUTED | CANCELLED | EXPIRED
    created_at      INTEGER NOT NULL,
    executed_at     INTEGER,
    cancelled_at    INTEGER
);
CREATE INDEX IF NOT EXISTS idx_trade_plans_user_date ON trade_plans(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_trade_plans_strategy ON trade_plans(strategy_name, status);

-- ── Signals (every signal generated by every strategy) ───────────────────
CREATE TABLE IF NOT EXISTS signals (
    signal_id       TEXT PRIMARY KEY,
    user_id         TEXT NOT NULL REFERENCES users(user_id),
    strategy_name   TEXT NOT NULL,
    symbol          TEXT NOT NULL,
    signal_type     TEXT NOT NULL,                -- BUY | SELL | EXIT_LONG | EXIT_SHORT | NO_ACTION
    strength        REAL NOT NULL DEFAULT 0.0,    -- 0.0 to 1.0 confidence
    price_at_signal REAL NOT NULL,
    indicator_data  TEXT NOT NULL DEFAULT '{}',   -- JSON: all indicator values at signal time
    skip_reason     TEXT NOT NULL DEFAULT '',      -- why signal was not acted on (risk, filter, etc.)
    acted_on        INTEGER NOT NULL DEFAULT 0,   -- 1 if a trade_plan was created
    created_at      INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_signals_user_date ON signals(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_signals_strategy ON signals(strategy_name, created_at);

-- ── Orders (sent to broker) ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS orders (
    order_id        TEXT PRIMARY KEY,             -- broker order ID or PAPER_xxxxx
    user_id         TEXT NOT NULL REFERENCES users(user_id),
    plan_id         TEXT REFERENCES trade_plans(plan_id),
    symbol          TEXT NOT NULL,
    side            TEXT NOT NULL,                -- BUY | SELL
    order_type      TEXT NOT NULL,                -- MARKET | LIMIT | SL | SL-M
    quantity        INTEGER NOT NULL,
    limit_price     REAL,
    trigger_price   REAL,
    status          TEXT NOT NULL DEFAULT 'PENDING',  -- PENDING | PLACED | PARTIAL | FILLED | CANCELLED | REJECTED
    broker_status   TEXT NOT NULL DEFAULT '',
    filled_qty      INTEGER NOT NULL DEFAULT 0,
    avg_fill_price  REAL,
    broker_msg      TEXT NOT NULL DEFAULT '',
    placed_at       INTEGER NOT NULL,
    filled_at       INTEGER,
    cancelled_at    INTEGER
);
CREATE INDEX IF NOT EXISTS idx_orders_user_date ON orders(user_id, placed_at);
CREATE INDEX IF NOT EXISTS idx_orders_plan ON orders(plan_id);

-- ── Trades (lifecycle: entry → exit → PnL) ──────────────────────────────
CREATE TABLE IF NOT EXISTS trades (
    trade_id        TEXT PRIMARY KEY,
    user_id         TEXT NOT NULL REFERENCES users(user_id),
    strategy_name   TEXT NOT NULL,
    symbol          TEXT NOT NULL,
    direction       TEXT NOT NULL,                -- LONG | SHORT
    quantity        INTEGER NOT NULL,
    entry_price     REAL NOT NULL,
    entry_time      INTEGER NOT NULL,             -- epoch ms
    exit_price      REAL,
    exit_time       INTEGER,
    stoploss_price  REAL,
    target_price    REAL,
    pnl_gross       REAL,                         -- before costs
    pnl_net         REAL,                         -- after all costs
    costs_total     REAL,                         -- brokerage + STT + charges
    exit_reason     TEXT NOT NULL DEFAULT '',      -- TARGET | STOPLOSS | TRAIL | FLATTEN | MANUAL | KILL
    entry_order_id  TEXT REFERENCES orders(order_id),
    exit_order_id   TEXT REFERENCES orders(order_id),
    plan_id         TEXT REFERENCES trade_plans(plan_id),
    trade_metadata  TEXT NOT NULL DEFAULT '{}',   -- JSON: extra details
    created_at      INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_trades_user_date ON trades(user_id, entry_time);
CREATE INDEX IF NOT EXISTS idx_trades_strategy ON trades(strategy_name, entry_time);

-- ── Positions (current open positions — upserted by engine) ──────────────
CREATE TABLE IF NOT EXISTS positions (
    position_id     TEXT PRIMARY KEY,
    user_id         TEXT NOT NULL REFERENCES users(user_id),
    strategy_name   TEXT NOT NULL,
    symbol          TEXT NOT NULL,
    direction       TEXT NOT NULL,                -- LONG | SHORT
    quantity        INTEGER NOT NULL,
    entry_price     REAL NOT NULL,
    current_price   REAL,
    unrealised_pnl  REAL,
    stoploss_price  REAL,
    target_price    REAL,
    trade_id        TEXT REFERENCES trades(trade_id),
    opened_at       INTEGER NOT NULL,
    updated_at      INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_positions_user ON positions(user_id);

-- ── Risk Events (breaches, kill switches, warnings) ──────────────────────
CREATE TABLE IF NOT EXISTS risk_events (
    event_id        TEXT PRIMARY KEY,
    user_id         TEXT NOT NULL REFERENCES users(user_id),
    event_type      TEXT NOT NULL,                -- DAILY_LIMIT_BREACH | STRATEGY_LIMIT | KILL_SWITCH | POSITION_LIMIT | MANUAL_KILL
    strategy_name   TEXT NOT NULL DEFAULT '',
    description     TEXT NOT NULL DEFAULT '',
    daily_pnl       REAL,
    threshold       REAL,
    action_taken    TEXT NOT NULL DEFAULT '',      -- KILL | PAUSE | ALERT | NONE
    created_at      INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_risk_events_user_date ON risk_events(user_id, created_at);

-- ── Commands (dashboard → engine control) ────────────────────────────────
CREATE TABLE IF NOT EXISTS commands (
    command_id      TEXT PRIMARY KEY,
    user_id         TEXT NOT NULL REFERENCES users(user_id),
    command_type    TEXT NOT NULL,                -- KILL | PAUSE | RESUME | FLATTEN | CANCEL_ORDER
    payload         TEXT NOT NULL DEFAULT '{}',   -- JSON: command-specific data
    status          TEXT NOT NULL DEFAULT 'PENDING',  -- PENDING | PROCESSED | FAILED
    created_at      INTEGER NOT NULL,
    processed_at    INTEGER
);
CREATE INDEX IF NOT EXISTS idx_commands_pending ON commands(status, created_at);

-- ── Backtest Runs (metadata for each backtest execution) ─────────────────
CREATE TABLE IF NOT EXISTS backtest_runs (
    run_id              TEXT PRIMARY KEY,
    user_id             TEXT NOT NULL REFERENCES users(user_id),
    strategy_name       TEXT NOT NULL,
    symbol_universe     TEXT NOT NULL DEFAULT '',  -- comma-separated symbols or 'NIFTY50'
    start_date          TEXT NOT NULL,             -- YYYY-MM-DD
    end_date            TEXT NOT NULL,
    initial_capital     REAL NOT NULL,
    final_capital       REAL,
    total_trades        INTEGER,
    winning_trades      INTEGER,
    losing_trades       INTEGER,
    win_rate            REAL,
    total_pnl           REAL,
    max_drawdown_pct    REAL,
    sharpe_ratio        REAL,
    profit_factor       REAL,
    avg_trade_pnl       REAL,
    max_consecutive_loss INTEGER,
    params_json         TEXT NOT NULL DEFAULT '{}', -- JSON: strategy params used
    results_json        TEXT NOT NULL DEFAULT '{}', -- JSON: detailed results
    created_at          INTEGER NOT NULL,
    duration_sec        REAL                        -- how long backtest took to run
);
CREATE INDEX IF NOT EXISTS idx_backtest_runs_strategy ON backtest_runs(strategy_name, created_at);

-- ── Backtest Trades (individual trades within a backtest run) ─────────────
CREATE TABLE IF NOT EXISTS backtest_trades (
    bt_trade_id     TEXT PRIMARY KEY,
    run_id          TEXT NOT NULL REFERENCES backtest_runs(run_id),
    symbol          TEXT NOT NULL,
    direction       TEXT NOT NULL,
    quantity        INTEGER NOT NULL,
    entry_price     REAL NOT NULL,
    entry_time      TEXT NOT NULL,                -- ISO datetime string
    exit_price      REAL NOT NULL,
    exit_time       TEXT NOT NULL,
    stoploss_price  REAL,
    target_price    REAL,
    pnl_gross       REAL NOT NULL,
    pnl_net         REAL NOT NULL,
    costs_total     REAL NOT NULL,
    exit_reason     TEXT NOT NULL,
    indicator_data  TEXT NOT NULL DEFAULT '{}'     -- JSON: indicator snapshot at entry
);
CREATE INDEX IF NOT EXISTS idx_bt_trades_run ON backtest_trades(run_id);

-- ── OHLCV Cache (downloaded historical data) ─────────────────────────────
CREATE TABLE IF NOT EXISTS ohlcv_cache (
    symbol          TEXT NOT NULL,
    timeframe       TEXT NOT NULL,                -- '1m' | '3m' | '5m' | '15m' | '1h' | '1d'
    timestamp       INTEGER NOT NULL,             -- epoch ms (candle open time)
    open            REAL NOT NULL,
    high            REAL NOT NULL,
    low             REAL NOT NULL,
    close           REAL NOT NULL,
    volume          INTEGER NOT NULL,
    PRIMARY KEY (symbol, timeframe, timestamp)
);
CREATE INDEX IF NOT EXISTS idx_ohlcv_symbol_tf ON ohlcv_cache(symbol, timeframe, timestamp);

-- ── Scanner Results Cache ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS scanner_cache (
    scan_date       TEXT NOT NULL,                -- YYYY-MM-DD
    strategy_name   TEXT NOT NULL,
    symbol          TEXT NOT NULL,
    score           REAL NOT NULL DEFAULT 0.0,
    rank            INTEGER NOT NULL DEFAULT 0,
    scan_data       TEXT NOT NULL DEFAULT '{}',   -- JSON: detailed scan metrics
    created_at      INTEGER NOT NULL,
    PRIMARY KEY (scan_date, strategy_name, symbol)
);

-- ── LLM Analysis Log (Phase 4) ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS llm_analysis (
    analysis_id     TEXT PRIMARY KEY,
    user_id         TEXT NOT NULL REFERENCES users(user_id),
    analysis_date   TEXT NOT NULL,                -- YYYY-MM-DD
    analysis_type   TEXT NOT NULL,                -- PRE_MARKET | INTRADAY_REVIEW | EOD_SUMMARY
    prompt_summary  TEXT NOT NULL DEFAULT '',
    response_text   TEXT NOT NULL DEFAULT '',
    model_used      TEXT NOT NULL DEFAULT '',
    tokens_used     INTEGER NOT NULL DEFAULT 0,
    cost_usd        REAL NOT NULL DEFAULT 0.0,
    market_context  TEXT NOT NULL DEFAULT '{}',   -- JSON: data fed to LLM
    recommendations TEXT NOT NULL DEFAULT '{}',   -- JSON: parsed LLM output
    created_at      INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_llm_analysis_date ON llm_analysis(analysis_date, analysis_type);

-- ── Insert default user ──────────────────────────────────────────────────
INSERT OR IGNORE INTO users (user_id, display_name, created_at)
VALUES ('default_user', 'Default Trader', strftime('%s', 'now') * 1000);

INSERT OR IGNORE INTO system_state (user_id, engine_status, updated_at)
VALUES ('default_user', 'STOPPED', strftime('%s', 'now') * 1000);
